package com.example.WorkHoursManager.services.performanceReferenceService;

import com.example.WorkHoursManager.vo.performanceReferenceVo.PerformanceReferenceReq;
import com.example.WorkHoursManager.vo.performanceReferenceVo.PerformanceReferenceResp;

public interface PerformanceReferenceService {
	
	public PerformanceReferenceResp setPerformanceReference(PerformanceReferenceReq performanceReferenceReq);
	public PerformanceReferenceResp getAllPerformanceReferences(PerformanceReferenceReq performanceReferenceReq);
	public PerformanceReferenceResp getPerformanceReferenceByCaseNo(PerformanceReferenceReq performanceReferenceReq);
	public PerformanceReferenceResp editPerformanceReference(PerformanceReferenceReq performanceReferenceReq);
	public PerformanceReferenceResp deletePerformanceReference(PerformanceReferenceReq performanceReferenceReq);
	
}
